sudo: false
addons:
  apt:
    packages:
    - binutils-dev
    - libcurl4-openssl-dev
    - libdw-dev
    - libiberty-dev
language: bash
cache:
  directories:
  - "${HOME}/google-cloud-sdk/"
  - "${HOME}/kcov/"
env:
- PATH=$PATH:${HOME}/google-cloud-sdk/bin:${HOME}/kcov/bin CLOUDSDK_CORE_DISABLE_PROMPTS=1
  kcov="kcov coverage --exclude-path=test,ops-gcp-kubernetes"
before_install:
- openssl aes-256-cbc -K $encrypted_3d71824c6097_key -iv $encrypted_3d71824c6097_iv
  -in credentials.tar.gz.enc -out credentials.tar.gz -d
- if [ ! -d "${HOME}/google-cloud-sdk/bin" ]; then rm -rf ${HOME}/google-cloud-sdk;
  curl https://sdk.cloud.google.com | bash; fi
- tar -xzf credentials.tar.gz
- gcloud auth activate-service-account --key-file client-secret.json
- if [ ! -d "${HOME}/kcov/bin" ]; then wget https://github.com/SimonKagstrom/kcov/archive/v34.tar.gz;
  tar xzf v34.tar.gz; cd kcov-34; mkdir build; cd build; cmake -DCMAKE_INSTALL_PREFIX=${HOME}/kcov
  ..; make; make install; cd ../..; rm -rf kcov-master; mkdir -p coverage; fi
install:
- gcloud -q components update
- gcloud -q components install kubectl
script:
- "${kcov} test/integration.sh"
after_success:
- bash <(curl -s https://codecov.io/bash)
notifications:
  slack:
    secure: UlUxZeyvJRAkByLtNL6kwI78/Sm4vcdDcNuVXRl//ZKAqj6vZICGM6ftA2OS8PD2Yo2hvM6jnQeuRPaPDJTtT4/uz68JVgCKOFega1RMW1h40vh1LIWSn8IXaMtIQZljfM21i29M0LBfu9LvkhlinpUDm82JyyMoo3O08MEJtMIUa1XSePWEWZ0tjrJo0NKMFPQN1b6bVBTuKQPoPsO2UNQWiOYUpiqPx7kX/bEgSQpR30AZt0xp5YgpswiDsqoU9hLgcjJbNTpqg2uwEoubhqduAf9vS+W2ZMc1IRPFMRYQUSFiWEPkJB2oUO1FiuvQ3zZoa7GVQAhl+8UufzRJE0ltPKuGqnOouX0KC7+u5M/LyZhsTZu1sR+4QikyO7213Hj/B/JlozCCjaBRpcOIv5Ix3uXmloJzwNa/Wy2GT0QGJrLYNTU/Z4sSvL8Mh2W3Sfkuj5wH0cbFRji79v6IjFwc/wwia4xSJiAvH04M6djLMMb3e5Wn1bItKQ+xkocE8SmJCCh/oFAV11DS7A+NhZrbjLvdmjNV3rBC4fjIKND7I5xwERA973comDUzJheXUx8WUeyoQOTIqMCVU3dkl1nxi/RqCwx9sv6K2diRHvxlUmqSsozYkSAyx/qNDjTi40b5jqft+P7+Fs1n9WWPcG1PsvyPDySLr1uLjubQqLA=
